# Generated by Django 4.2.1 on 2023-05-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(blank=True, max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images/teacher/')),
                ('description', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.CharField(blank=True, max_length=20)),
                ('twitter', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=20)),
                ('telegram', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
            },
        ),
    ]
