# Generated by Django 4.2.1 on 2023-05-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='postcomments',
            name='name',
        ),
        migrations.AddField(
            model_name='postcomments',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
