# Generated by Django 4.2.1 on 2023-05-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_postcomments_email_remove_postcomments_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/user/avatar/'),
        ),
    ]
