# Generated by Django 4.2.1 on 2023-05-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, upload_to='videos/')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
            },
        ),
    ]
