# Generated by Django 4.2.1 on 2023-05-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=0, upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
    ]
