# Generated by Django 4.2.1 on 2023-05-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_video_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='Videos',
        ),
    ]
