# Generated by Django 4.2.1 on 2023-05-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_video_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
    ]
